### ISSUE TITLE
AJAX loading indicator

### ISSUE THREAD

**Issue by jessevondoom** [cashmusic/platform#332]
Thinking we need something to indicate that a page load is happening. Right now there's the faded page elements but something animated/active would go a long way. I'd like to add a rotating image to that effect so it's really clear there's action going on. 

``` CSS
.rotate {-webkit-animation:spin .8s infinite linear;animation:spin .8s infinite linear;}
@-webkit-keyframes spin {100%{-webkit-transform:rotate(360deg);}}
@-moz-keyframes spin {100%{-moz-transform:rotate(360deg);}}
@keyframes spin {100%{-moz-transform:rotate(360deg);-o-transform:rotate(360deg);transform:rotate(360deg);}}
```
